# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socios', models.IntegerField(choices=[(1, 'Si'), (2, 'No')])),
                ('no_socios', models.IntegerField(choices=[(1, 'Si'), (2, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ApoyoDonante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Areas de apoyo',
            },
        ),
        migrations.CreateModel(
            name='EmpleadosOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.IntegerField(verbose_name=((1, 'Tiempo completo'), (2, 'Tiempo parcial'), (3, 'Temporales')))),
                ('total_hombre', models.IntegerField()),
                ('total_mujer', models.IntegerField()),
                ('adultos_hombre', models.IntegerField()),
                ('adultos_mujer', models.IntegerField()),
                ('jovenes_hombre', models.IntegerField()),
                ('jovenes_mujer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vias_finca', models.CharField(max_length=250)),
                ('transitable_finca', models.IntegerField(choices=[(1, 'Transitable todo el tiempo'), (2, 'Transitable solo en verano')])),
                ('vias_oficina', models.CharField(max_length=250)),
                ('transitable_oficina', models.IntegerField(choices=[(1, 'Transitable todo el tiempo'), (2, 'Transitable solo en verano')])),
                ('distancia', models.CharField(max_length=150)),
                ('acceso_internet', models.CharField(choices=[(1, 'Si'), (2, 'No')], max_length=150)),
                ('transporte_publico', models.CharField(choices=[(1, 'Si'), (2, 'No')], max_length=150)),
                ('red_movil', models.CharField(choices=[(1, 'Si'), (2, 'No')], max_length=150)),
                ('electricidad', models.CharField(choices=[(1, 'Si'), (2, 'No')], max_length=150)),
                ('agua_potable', models.CharField(choices=[(1, 'Si'), (2, 'No')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='MiembrosOficiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.IntegerField(choices=[(1, 'N\xfamero de miembros registrados oficialmente'), (2, 'N\xfamero de miembros en proceso de afiliaci\xf3n')])),
                ('total_hombre', models.IntegerField()),
                ('total_mujer', models.IntegerField()),
                ('activos_hombre', models.IntegerField()),
                ('activos_mujer', models.IntegerField()),
                ('jovenes_hombre', models.IntegerField()),
                ('jovenes_mujer', models.IntegerField()),
                ('inactivos_hombre', models.IntegerField()),
                ('inactivos_mujer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NumeroCooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cooperativa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacionPertenece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Organizaciones a la que pertenece',
            },
        ),
        migrations.CreateModel(
            name='ProductoresProveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.IntegerField(verbose_name=((1, 'N\xfamero de miembros registrados oficialmente'),))),
                ('total_hombre', models.IntegerField()),
                ('total_mujer', models.IntegerField()),
                ('activos_hombre', models.IntegerField()),
                ('activos_mujer', models.IntegerField()),
                ('jovenes_hombre', models.IntegerField()),
                ('jovenes_mujer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectoresProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.IntegerField(choices=[(1, 'Agricultura'), (2, 'Ganader\xeda'), (3, 'Forestal'), (4, 'Acuicultura')])),
                ('producto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socios', models.IntegerField(choices=[(1, 'Si'), (2, 'No')])),
                ('no_socios', models.IntegerField(choices=[(1, 'Si'), (2, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='organizacion',
            options={'verbose_name': 'Organizaci\xf3n', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipoorganizacion',
            options={'verbose_name': 'Tipo de Organizaci\xf3n', 'verbose_name_plural': 'Tipos de Organizaciones'},
        ),
        migrations.AddField(
            model_name='organizacion',
            name='apoyo',
            field=models.IntegerField(blank=True, choices=[(1, 'Si'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='en_operaciones',
            field=models.IntegerField(blank=True, choices=[(1, 'Si'), (2, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='incorporacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='A\xf1o de incorporaci\xf3n'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='licencia',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='No. de licencia empresarial'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='oficina_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='oficina_numero',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Pais'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='persona1_cargo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='persona1_contacto',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='persona1_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='persona1_telefono',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='persona2_cargo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='persona2_contacto',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='persona2_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='persona2_telefono',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='personeria',
            field=models.IntegerField(blank=True, choices=[(1, 'Si'), (2, 'No'), (3, 'En proceso')], null=True, verbose_name='Cuenta con personer\xeda Jur\xeddica'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='red_social1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Red Social 1'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='red_social2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Red Social 2'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='red_social3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Red Social 3'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='red_social4',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Red Social 4'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tributaria',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='No. de identificaci\xf3n tributaria'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Servicios'),
        ),
        migrations.AddField(
            model_name='sectoresproductos',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
        migrations.AddField(
            model_name='productoresproveedores',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
        migrations.AddField(
            model_name='organizacionpertenece',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
        migrations.AddField(
            model_name='organizacionpertenece',
            name='organizaciones',
            field=models.ManyToManyField(to='organizaciones.Instituciones'),
        ),
        migrations.AddField(
            model_name='numerocooperativa',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
        migrations.AddField(
            model_name='miembrosoficiales',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
        migrations.AddField(
            model_name='infraestructura',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
        migrations.AddField(
            model_name='empleadosorganizacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
        migrations.AddField(
            model_name='apoyodonante',
            name='areas',
            field=models.ManyToManyField(to='organizaciones.Areas'),
        ),
        migrations.AddField(
            model_name='apoyodonante',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Instituciones'),
        ),
        migrations.AddField(
            model_name='apoyodonante',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Actividades'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
    ]
