# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0002_auto_20170512_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadosorganizacion',
            name='opcion',
            field=models.IntegerField(choices=[(1, 'Tiempo completo'), (2, 'Tiempo parcial'), (3, 'Temporales')]),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='acceso_internet',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='agua_potable',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='electricidad',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='red_movil',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='transporte_publico',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productoresproveedores',
            name='opcion',
            field=models.IntegerField(choices=[(1, 'N\xfamero de miembros registrados oficialmente')]),
        ),
    ]
