# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0003_auto_20170517_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividad'},
        ),
        migrations.AlterModelOptions(
            name='apoyodonante',
            options={'verbose_name_plural': '17.Recibe apoyo de donantes u otras instituciones'},
        ),
        migrations.AlterModelOptions(
            name='empleadosorganizacion',
            options={'verbose_name_plural': '22.Empleados en la organizaci\xf3n'},
        ),
        migrations.AlterModelOptions(
            name='infraestructura',
            options={'verbose_name_plural': 'III.Informaci\xf3n de infraestructura'},
        ),
        migrations.AlterModelOptions(
            name='miembrosoficiales',
            options={'verbose_name_plural': '19.Miembros'},
        ),
        migrations.AlterModelOptions(
            name='numerocooperativa',
            options={'verbose_name_plural': '20.N\xfamero de cooperativas que son miembros'},
        ),
        migrations.AlterModelOptions(
            name='organizacionpertenece',
            options={'verbose_name_plural': '18.Organizaciones a la que pertenece'},
        ),
        migrations.AlterModelOptions(
            name='productoresproveedores',
            options={'verbose_name_plural': '21.Productores proveedores no socios'},
        ),
        migrations.AlterModelOptions(
            name='sectoresproductos',
            options={'verbose_name_plural': '31.Sectores'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='sectoresproductos',
            name='producto',
        ),
        migrations.AddField(
            model_name='productos',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.SectoresProductos'),
        ),
    ]
