# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0006_auto_20170724_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaIngresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=50, verbose_name='A\xf1o')),
                ('ingresos', models.FloatField()),
                ('egresos', models.FloatField()),
                ('adjuntar_archivo', models.FileField(upload_to='/documentosIngresos')),
            ],
            options={
                'verbose_name_plural': 'Tabla de ingresos',
            },
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': '32.Actividades'},
        ),
        migrations.AlterModelOptions(
            name='apoyodonante',
            options={'verbose_name_plural': '17.1 \xc1rea reciben apoyo'},
        ),
        migrations.AlterModelOptions(
            name='miembrosoficiales',
            options={'verbose_name_plural': '19.Miembros (directivos de la OP+ indirectos v\xedas Sucursal)'},
        ),
        migrations.AlterModelOptions(
            name='sectoresproductos',
            options={'verbose_name_plural': '31.Cultivo principal'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': '32.1 Servicios'},
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='distancia',
            field=models.CharField(max_length=150, verbose_name='Distancia al centro de abastecimiento (Km)'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='vias_finca',
            field=models.CharField(max_length=250, verbose_name='V\xedas de acceso a finca'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='vias_oficina',
            field=models.CharField(max_length=250, verbose_name='V\xedas de acceso a la oficina'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='apoyo',
            field=models.IntegerField(blank=True, choices=[(1, 'Si'), (2, 'No')], null=True, verbose_name='Recibe apoyo de donantes u otras instituciones'),
        ),
        migrations.AddField(
            model_name='tablaingresos',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
    ]
