# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuenoNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(choices=[(1, 'Arrendada'), (2, 'Tierra Ind/comunal'), (3, 'Promesa de venta'), (4, 'Sin escritura'), (5, 'Prestada'), (6, 'Colectivo/Cooperativa')])),
            ],
        ),
        migrations.CreateModel(
            name='DuenoSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.IntegerField(choices=[(1, 'A nombre del hombre'), (2, 'A nombre de la mujer'), (3, 'A nombre de los hijos'), (4, 'Mancomunado')])),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre y apellido')),
                ('fecha_naciemiento', models.DateField()),
                ('anios_vinculacion', models.FloatField(verbose_name='A\xf1os de vinculaci\xf3n')),
                ('dueno_propiedad', models.IntegerField(choices=[(1, 'Si'), (0, 'No')])),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Organizacion', verbose_name='Organizaci\xf3n a la que pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='TipoOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.TipoOrganizacion'),
        ),
        migrations.AddField(
            model_name='duenosi',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Productor'),
        ),
        migrations.AddField(
            model_name='duenono',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Productor'),
        ),
    ]
