# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuenoNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(choices=[(1, 'Arrendada'), (2, 'Tierra Ind/comunal'), (3, 'Promesa de venta'), (4, 'Sin escritura'), (5, 'Prestada'), (6, 'Colectivo/Cooperativa')])),
            ],
            options={
                'verbose_name': 'En el caso que diga NO, especifique la situaci\xf3n',
                'verbose_name_plural': 'En el caso que diga NO, especifique la situaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='DuenoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.IntegerField(choices=[(1, 'Si'), (2, 'No')])),
            ],
            options={
                'verbose_name': '8. \xbfEs due\xf1o de la propiedad/finca?',
                'verbose_name_plural': '8. \xbfEs due\xf1o de la propiedad/finca?',
            },
        ),
        migrations.CreateModel(
            name='DuenoSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.IntegerField(choices=[(1, 'A nombre del hombre'), (2, 'A nombre de la mujer'), (3, 'A nombre de los hijos'), (4, 'Mancomunado')])),
            ],
            options={
                'verbose_name': 'En el caso SI, indique a nombre de quien est\xe1',
                'verbose_name_plural': 'En el caso SI, indique a nombre de quien est\xe1',
            },
        ),
        migrations.CreateModel(
            name='MiembrosFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembros', models.IntegerField(choices=[(1, 'Hombres > 31 a\xf1os'), (2, 'Mujeres > 31 a\xf1os'), (3, 'Ancianos > 64 a\xf1os'), (4, 'Ancianas > 64 a\xf1os'), (5, 'Mujer joven de 19 a 30 a\xf1os'), (6, 'Hombre joven de 19 a 30 a\xf1os'), (7, 'Mujer adolescente 13 a 18 a\xf1os'), (8, 'Hombre adolescente 13 a 18 a\xf1os'), (9, 'Ni\xf1as 5 a 12 a\xf1os'), (10, 'Ni\xf1os 5 a 12 a\xf1os'), (11, 'Ni\xf1as 0 a 4 a\xf1os'), (12, 'Ni\xf1os 0 a 4 a\xf1os')])),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': '7. Cantidad de miembros de la familia',
                'verbose_name_plural': '7. Cantidad de miembros de la familia',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='1. Nombre y apellido')),
                ('fecha_naciemiento', models.DateField(verbose_name='2. Fecha de nacimiento')),
                ('sexo', models.IntegerField(choices=[(1, 'Mujer'), (2, 'Hombre')], verbose_name='3. Sexo')),
                ('anios_vinculacion', models.FloatField(verbose_name='6. A\xf1os de vinculaci\xf3n')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Organizacion', verbose_name='4. Organizaci\xf3n a la que pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='TipoOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.TipoOrganizacion'),
        ),
        migrations.AddField(
            model_name='miembrosfamilia',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Productor'),
        ),
        migrations.AddField(
            model_name='duenosi',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Productor'),
        ),
        migrations.AddField(
            model_name='duenopropiedad',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Productor'),
        ),
        migrations.AddField(
            model_name='duenono',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Productor'),
        ),
    ]
