# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField(choices=[(1, 'Grupo de intervenci\xf3n'), (2, 'Grupo de control')])),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Encuestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='productor',
            name='departamento',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='pais', default=1, on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productor',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='departamento', default=1, on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productor',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lugar.Pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productor',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion', verbose_name='4. Organizaci\xf3n a la que pertenece'),
        ),
        migrations.DeleteModel(
            name='Organizacion',
        ),
        migrations.DeleteModel(
            name='TipoOrganizacion',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='encuestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuestador'),
        ),
    ]
