# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresosfamilia',
            name='respuesta',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5),
        ),
    ]
