# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0002_auto_20170327_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='edad',
            field=models.IntegerField(choices=[(1, 'Menor 35'), (2, 'Mayor 35')], default=1, editable=False),
            preserve_default=False,
        ),
    ]
