# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0002_auto_20170315_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(help_text='Mz', verbose_name='\xc1rea')),
            ],
            options={
                'verbose_name': '9. \xc1rea total de propiedad/finca',
                'verbose_name_plural': '9. \xc1rea total de propiedad/finca',
            },
        ),
        migrations.CreateModel(
            name='BPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higiene_trabajadores', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Lavado de manos'), (2, 'Dispone de letrina'), (3, 'Obreros no poseen enfermedades infecciosas')], max_length=5, verbose_name='3. Higiene de los trabajadores')),
                ('sustancias_quimicas', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Bodega de plaguicidas e insumos'), (2, '\xc1rea de preparaci\xf3n y mezclado de plaguicidas'), (3, 'Equipo protector para las personas que manipulan plaguicidas')], max_length=5, verbose_name='4. Uso correcto de sustancias qu\xedmicas en')),
                ('registro_rastreabilidad', models.BooleanField(verbose_name='Registro y Rastreabilidad')),
            ],
            options={
                'verbose_name': '11. \xbfSi tiene Buenas Pr\xe1cticas Agr\xedcolas (BPA), indique el tipo de pr\xe1cticas que implementa',
                'verbose_name_plural': '11. \xbfSi tiene Buenas Pr\xe1cticas Agr\xedcolas (BPA), indique el tipo de pr\xe1cticas que implementa',
            },
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificacion', models.IntegerField(choices=[(1, 'Si'), (2, 'No')])),
            ],
            options={
                'verbose_name': '10. \xbfLa propiedad/ finca tiene certificaci\xf3n?',
                'verbose_name_plural': '10. \xbfLa propiedad/ finca tiene certificaci\xf3n?',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Certificado que posee el productor',
                'verbose_name_plural': 'Certificados que posee el productor',
            },
        ),
        migrations.CreateModel(
            name='CertificadoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.ManyToManyField(to='productores.Certificado')),
            ],
            options={
                'verbose_name': '10.2_En el caso SI, indique el tipo de certificaci\xf3n y nombre de la empresa',
                'verbose_name_plural': '10.2_En el caso SI, indique el tipo de certificaci\xf3n y nombre de la empresa',
            },
        ),
        migrations.CreateModel(
            name='DistribucionFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.IntegerField(choices=[(1, 'Bosque'), (2, 'Potrero'), (3, 'Cultivo anual'), (4, 'Cultivo asociado'), (5, 'Plantaci\xf3n forestal'), (6, 'Sistema agroforestal'), (7, 'Sistema silvopastoril')])),
                ('cantidad', models.FloatField()),
            ],
            options={
                'verbose_name': '9.1 Distribuci\xf3n de la tierra en la propiedad/finca en Mz',
                'verbose_name_plural': '9.1 Distribuci\xf3n de la tierra en la propiedad/finca en Mz',
            },
        ),
        migrations.CreateModel(
            name='EliminacionFocos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Eliminaci\xf3n de focos de contaminaci\xf3n dentro y fuera del cultivo',
                'verbose_name_plural': 'Eliminaci\xf3n de focos de contaminaci\xf3n dentro y fuera del cultivo',
            },
        ),
        migrations.CreateModel(
            name='EmpresaCertifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Empresa que certifica al productor',
                'verbose_name_plural': 'Empresas que certifican al productor',
            },
        ),
        migrations.CreateModel(
            name='ProteccionFuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Protecci\xf3n de fuentes y calidad de agua (pozos, r\xedos)',
                'verbose_name_plural': 'Protecci\xf3n de fuentes y calidad de agua (pozos, r\xedos)',
            },
        ),
        migrations.CreateModel(
            name='TipoCertificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Colectiva'), (2, 'Individual')])),
            ],
            options={
                'verbose_name': '10.1_En el caso SI, indique si la certificaci\xf3n es',
                'verbose_name_plural': '10.1_En el caso SI, indique si la certificaci\xf3n es',
            },
        ),
        migrations.AddField(
            model_name='encuesta',
            name='productor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productores.Productor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocertificacion',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='distribucionfinca',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='certificadoempresa',
            name='empresa',
            field=models.ManyToManyField(to='productores.EmpresaCertifica'),
        ),
        migrations.AddField(
            model_name='certificadoempresa',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='bpa',
            name='elimincacion_focos',
            field=models.ManyToManyField(blank=True, to='productores.EliminacionFocos', verbose_name='1. Eliminaci\xf3n de focos de contaminaci\xf3n dentro y fuera del cultivo'),
        ),
        migrations.AddField(
            model_name='bpa',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='bpa',
            name='proteccion_fuentes',
            field=models.ManyToManyField(blank=True, to='productores.ProteccionFuentes', verbose_name='2. Protecci\xf3n de fuentes y calidad de agua (pozos, r\xedos)'),
        ),
        migrations.AddField(
            model_name='areafinca',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
    ]
