# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0003_auto_20170315_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('unidad_medida', models.IntegerField(choices=[(1, 'Lb'), (2, 'Unidades'), (3, 'Docena'), (2, 'Quintal')])),
                ('hortaliza', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_colectivo', models.IntegerField(choices=[(1, 'Individual'), (2, 'Asocio')])),
                ('area_sembrada', models.FloatField(verbose_name='\xc1rea sembrada (Mz)')),
                ('area_cosechada', models.FloatField(verbose_name='\xc1rea cosechada (Mz)')),
                ('cantidad_cosechada', models.FloatField(verbose_name='Cantidad cosechada')),
                ('consumo', models.FloatField(verbose_name='Consumo de la familia')),
                ('procesamiento', models.FloatField()),
                ('venta', models.FloatField()),
                ('costo_produccion', models.FloatField(verbose_name='Costo producci\xf3n por Mz (Moneda local)')),
                ('costo_inversion', models.FloatField(verbose_name='Costo inversi\xf3n por Mz (Moneda local)')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Cultivo')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name': '12. Indique producci\xf3n y destino de cada uno de los cultivos establecidos en la propiedad/finca',
                'verbose_name_plural': '12. Indique producci\xf3n y destino de cada uno de los cultivos establecidos en la propiedad/finca',
            },
        ),
    ]
