# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
        ('productores', '0004_auto_20170406_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPAPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': '\xbfAplica Buenas Pr\xe1cticas Agr\xedcolas (BPA)?',
            },
        ),
        migrations.CreateModel(
            name='Promedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('precio_promedio', models.FloatField()),
                ('costo_promedio', models.FloatField()),
                ('rendimiento_promedio', models.FloatField()),
                ('ingreso_promedio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PromedioNacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.IntegerField(choices=[(1, 'Caf\xe9'), (2, 'Cacao'), (3, 'Hortaliza')])),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Pais')),
            ],
            options={
                'verbose_name': 'Promedio Nacional',
                'verbose_name_plural': 'Promedios Nacionales',
            },
        ),
        migrations.AddField(
            model_name='promedio',
            name='promedio_nacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.PromedioNacional'),
        ),
    ]
