# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0004_cultivo_produccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Cultivo')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.IntegerField(choices=[(1, 'Mercado tradicional'), (2, 'Cooperativa')])),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('destino_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.DestinoProduccion')),
            ],
        ),
    ]
