# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0005_auto_20170420_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpapregunta',
            options={'verbose_name_plural': '11. \xbfAplica Buenas Pr\xe1cticas Agr\xedcolas (BPA)?'},
        ),
        migrations.AlterModelOptions(
            name='promedio',
            options={'verbose_name': 'Promedio', 'verbose_name_plural': 'Promedios'},
        ),
        migrations.AddField(
            model_name='mercado',
            name='ingreso',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='practicasmip',
            name='control_malezas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Control o pre germinaci\xf3n de malezas (15 d\xedas antes de la siembra o transplante)'), (2, 'Manejo de rondas')], max_length=3, null=True, verbose_name='Control de malezas'),
        ),
        migrations.AlterField(
            model_name='practicasmip',
            name='control_plagas_enfermedades',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Muestreo de plagas de suelo al momento de la preparaci\xf3n del terreno'), (2, 'Control adecuado de plagas del suelo'), (3, 'Uso de insecticidas sist\xe9micos como preventivo'), (4, 'Uso de Agribon en cultivos que lo ameriten'), (5, 'Uso de Trampas amarillas o pegajosas'), (6, 'Eliminaci\xf3n de plantas enfermas'), (7, 'Poda sanitaria en cultivos que as\xed lo ameriten'), (8, 'Trampas olorosas'), (9, 'Uso de \xe1cido salic\xedlico o fosfonatos de potasio (Estimuladores de las defensas de la planta)'), (10, 'Eliminaci\xf3n de fruto da\xf1ado (gusanos, picudo)'), (11, 'Desinfecci\xf3n de estacas y mecates de amarres, si son reutilizados. En cultivos que necesiten tutoreo'), (12, 'Muestreo de plagas y enfermedades (AAE)'), (13, 'Uso de pl\xe1stico de cobertura en cultivos que lo amerite'), (14, 'Control manual de plagas (larvas o huevos)'), (15, 'Utilizaci\xf3n de equipos de protecci\xf3n para aplicaci\xf3n de plaguicidas'), (16, 'Utilizaci\xf3n de productos coadyugantes (adherente, dispersables, penetrantes)'), (17, 'Calibraci\xf3n del equipo de aplicaci\xf3n'), (18, 'Utilizaci\xf3n de productos biol\xf3gicos'), (19, 'Eliminaci\xf3n inmediata de rastrojo'), (20, 'Rotaci\xf3n de cultivo'), (21, 'Regulaci\xf3n de pH de agua para la aplicaci\xf3n de plaguicidas, con un rango de pH de 5.5-7')], max_length=53, null=True, verbose_name='Control de plagas y enfermedades'),
        ),
        migrations.AlterField(
            model_name='practicasmip',
            name='densidad_siembra',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Distanciamiento de planta adecuado'), (2, 'Densidad de planta adecuada')], max_length=3, null=True, verbose_name='Densidad de siembra correcta'),
        ),
        migrations.AlterField(
            model_name='practicasmip',
            name='fertilizacion_adecuada',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Plan de fertilizaci\xf3n seg\xfan la demanda del cultivo'), (2, 'Uso de Soluci\xf3n Arrancadora'), (3, 'Fertilizaci\xf3n diluida')], max_length=5, null=True, verbose_name='Fertilizaci\xf3n Adecuada'),
        ),
        migrations.AlterField(
            model_name='practicasmip',
            name='material_siembra_sano',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Material de siembra de buena calidad(libre de plagas y enfermedades)'), (2, 'Uso de variedades tolerantes,variedades mejoradas o criolla seleccionada'), (3, 'Uso de pl\xe1ntulas de calidad (Libre de plagas y enfermedades, vigorosas)')], max_length=5, null=True, verbose_name='Material de siembra sano'),
        ),
        migrations.AlterField(
            model_name='practicasmip',
            name='preparacion_terreno',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Acciones correctivas al suelo (Incorporaci\xf3n de cal o materia org\xe1nica)'), (2, 'Preparaci\xf3n del terreno al menos 21 d\xedas antes de la siembra'), (3, 'Siembra con curvas a nivel o desnivel en terrenos con pendiente'), (4, 'Barreras vivas (Establecer Las 15-20 d\xedas antes de siembra o transplante)'), (5, 'Siembra en camas altas (mejor crecimiento radicular, absorci\xf3n)')], max_length=9, null=True, verbose_name='Preparaci\xf3n del Terreno'),
        ),
    ]
