# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0005_destinoproduccion_mercado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteIngresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente_ingreso', models.CharField(choices=[('Asalariado', 'Asalariado'), ('Jornalero', 'Jornalero'), ('Alquiler', 'Alquiler'), ('Negocio propio', 'Negocio propio'), ('Remesas', 'Remesas'), ('Otros', 'Otros')], max_length=50)),
                ('cantidad_mensual', models.IntegerField(verbose_name='Cantidad total mensual (Moneda local)')),
                ('cantidad_veces', models.IntegerField(verbose_name='Cantidad de veces en el a\xf1o que recibe esta cantidad')),
                ('hombres', models.IntegerField(verbose_name='Cantidad de miembros hombres de la familia involucrados')),
                ('mujeres', models.IntegerField(verbose_name='Cantidad de miembros mujeres de la familia involucrados')),
            ],
            options={
                'verbose_name': 'Fuente de ingreso',
                'verbose_name_plural': '15.1. Si la respuesta es SI puede indicar la fuente',
            },
        ),
        migrations.CreateModel(
            name='IngresosFamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.IntegerField(choices=[('Si', 'Si'), ('No', 'No')])),
            ],
            options={
                'verbose_name_plural': '15. \xbfLa familia percibe otros ingresos diferentes a la actividad agr\xedcola?',
            },
        ),
        migrations.CreateModel(
            name='IngresosOtrosCultivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_anual', models.FloatField(verbose_name='Ingreso anual (moneda local)')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': '14. \xbfIndique los ingresos totales por otros cultivos en la propiedad/finca?',
            },
        ),
        migrations.AlterModelOptions(
            name='destinoproduccion',
            options={'verbose_name': 'Cultivo', 'verbose_name_plural': '13. Por tipo de cultivo, seg\xfan la cantidad destinada la venta, indique cantidad vendida por tipo de mercado y precio(moneda local)'},
        ),
        migrations.AlterField(
            model_name='bpa',
            name='higiene_trabajadores',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lavado de manos', 'Lavado de manos'), ('Dispone de letrina', 'Dispone de letrina'), ('Obreros no poseen enfermedades infecciosas', 'Obreros no poseen enfermedades infecciosas')], max_length=77, verbose_name='3. Higiene de los trabajadores'),
        ),
        migrations.AlterField(
            model_name='bpa',
            name='sustancias_quimicas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bodega de plaguicidas e insumos', 'Bodega de plaguicidas e insumos'), ('\xc1rea de preparaci\xf3n y mezclado de plaguicidas', '\xc1rea de preparaci\xf3n y mezclado de plaguicidas'), ('Equipo protector para las personas que manipulan plaguicidas', 'Equipo protector para las personas que manipulan plaguicidas')], max_length=138, verbose_name='4. Uso correcto de sustancias qu\xedmicas en'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='certificacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='unidad_medida',
            field=models.CharField(choices=[('Lb', 'Lb'), ('Unidades', 'Unidades'), ('Docena', 'Docena'), ('Quintal', 'Quintal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='distribucionfinca',
            name='seleccion',
            field=models.CharField(choices=[('Bosque', 'Bosque'), ('Potrero', 'Potrero'), ('Cultivo anual', 'Cultivo anual'), ('Cultivo asociado', 'Cultivo asociado'), ('Plantaci\xf3n forestal', 'Plantaci\xf3n forestal'), ('Sistema agroforestal', 'Sistema agroforestal'), ('Sistema silvopastoril', 'Sistema silvopastoril')], max_length=50),
        ),
        migrations.AlterField(
            model_name='duenono',
            name='no',
            field=models.CharField(choices=[('Arrendada', 'Arrendada'), ('Tierra Ind/comunal', 'Tierra Ind/comunal'), ('Promesa de venta', 'Promesa de venta'), ('Sin escritura', 'Sin escritura'), ('Prestada', 'Prestada'), ('Colectivo/Cooperativa', 'Colectivo/Cooperativa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='duenopropiedad',
            name='respuesta',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='duenosi',
            name='si',
            field=models.CharField(choices=[('A nombre del hombre', 'A nombre del hombre'), ('A nombre de la mujer', 'A nombre de la mujer'), ('A nombre de los hijos', 'A nombre de los hijos'), ('Mancomunado', 'Mancomunado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='grupo',
            field=models.CharField(choices=[('Grupo de intervenci\xf3n', 'Grupo de intervenci\xf3n'), ('Grupo de control', 'Grupo de control')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mercado',
            name='mercado',
            field=models.CharField(choices=[('Mercado tradicional', 'Mercado tradicional'), ('Cooperativa', 'Cooperativa'), ('Ferias', 'Ferias'), ('Empresas procesadoras', 'Empresas procesadoras'), ('Empresas comercializadoras', 'Empresas comercializadoras'), ('Empresas exportadoras', 'Empresas exportadoras'), ('Supermercados', 'Supermercados'), ('Cadena de restaurantes', 'Cadena de restaurantes'), ('Intermediarios', 'Intermediarios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='miembrosfamilia',
            name='miembros',
            field=models.CharField(choices=[('Hombres > 31 a\xf1os', 'Hombres > 31 a\xf1os'), ('Mujeres > 31 a\xf1os', 'Mujeres > 31 a\xf1os'), ('Ancianos > 64 a\xf1os', 'Ancianos > 64 a\xf1os'), ('Ancianas > 64 a\xf1os', 'Ancianas > 64 a\xf1os'), ('Mujer joven de 19 a 30 a\xf1os', 'Mujer joven de 19 a 30 a\xf1os'), ('Hombre joven de 19 a 30 a\xf1os', 'Hombre joven de 19 a 30 a\xf1os'), ('Mujer adolescente 13 a 18 a\xf1os', 'Mujer adolescente 13 a 18 a\xf1os'), ('Hombre adolescente 13 a 18 a\xf1os', 'Hombre adolescente 13 a 18 a\xf1os'), ('Ni\xf1as 5 a 12 a\xf1os', 'Ni\xf1as 5 a 12 a\xf1os'), ('Ni\xf1os 5 a 12 a\xf1os', 'Ni\xf1os 5 a 12 a\xf1os'), ('Ni\xf1as 0 a 4 a\xf1os', 'Ni\xf1as 0 a 4 a\xf1os'), ('Ni\xf1os 0 a 4 a\xf1os', 'Ni\xf1os 0 a 4 a\xf1os')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='forma_colectivo',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Asocio', 'Asocio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productor',
            name='sexo',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre')], max_length=5, verbose_name='3. Sexo'),
        ),
        migrations.AlterField(
            model_name='tipocertificacion',
            name='tipo',
            field=models.CharField(choices=[('Colectiva', 'Colectiva'), ('Individual', 'Individual')], max_length=50),
        ),
        migrations.AddField(
            model_name='ingresosotroscultivos',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Cultivo'),
        ),
        migrations.AddField(
            model_name='ingresosotroscultivos',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='ingresosfamilia',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='fuenteingresos',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
    ]
