# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0006_auto_20170316_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesRiegos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_riego', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5, verbose_name='17. \xbfDispone de sistema de riego?')),
                ('estado_sistema_riego', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=50, verbose_name='17.2 \xbfCual es el estado del sistema de riego?')),
                ('area_sistema_riego', models.FloatField(verbose_name='17.3 \xbfCantidad de \xe1rea en mz  bajo sistema de riego?')),
                ('cosecha_agua', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5, verbose_name='18 \xbfTiene cosecha de agua?')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Condiciones de riegos de la propiedad/finca',
            },
        ),
        migrations.CreateModel(
            name='IngresosActividadesGanaderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(choices=[('Ganader\xeda menor', 'Ganader\xeda menor'), ('Ganader\xeda mayor', 'Ganader\xeda mayor'), ('Procesamiento de productos agr\xedcolas', 'Procesamiento de productos agr\xedcolas')], max_length=50)),
                ('cantidad_mensual', models.IntegerField(verbose_name='Cantidad total mensual (Moneda local)')),
                ('cantidad_veces', models.IntegerField(verbose_name='Cantidad de veces en el a\xf1o que recibe esta cantidad')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name': 'Fuente de ingreso',
                'verbose_name_plural': '16. Otros ingresos por actividades de ganader\xeda (mayor y menor) y procesamiento de productos agropecuarios',
            },
        ),
        migrations.CreateModel(
            name='TipoSistemaRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tipo de sistema de riego',
                'verbose_name_plural': 'Tipos de sistemas de riego',
            },
        ),
        migrations.AlterModelOptions(
            name='distribucionfinca',
            options={'verbose_name': 'Distribuci\xf3n de la tierra', 'verbose_name_plural': '9.1 Distribuci\xf3n de la tierra en la propiedad/finca en Mz'},
        ),
        migrations.AlterModelOptions(
            name='produccion',
            options={'verbose_name': 'Cultivo', 'verbose_name_plural': '12. Indique producci\xf3n y destino de cada uno de los cultivos establecidos en la propiedad/finca'},
        ),
        migrations.AddField(
            model_name='condicionesriegos',
            name='tipo_sistema_riego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.TipoSistemaRiego', verbose_name='17.1 \xbfTipo de sistema de riego posee?'),
        ),
    ]
