# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0006_auto_20170426_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='rechazo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promedio',
            name='anio',
            field=models.IntegerField(verbose_name='A\xf1o'),
        ),
        migrations.AlterField(
            model_name='promedionacional',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Cultivo'),
        ),
    ]
