# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Aspectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Aspecto',
                'verbose_name_plural': 'Aspectos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaGastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gatos',
            },
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='A\xf1o')),
                ('responsable', models.CharField(max_length=250, verbose_name='Nombre del responsable')),
                ('moneda', models.IntegerField(choices=[(1, 'USD$')])),
                ('grupo', models.CharField(max_length=250, verbose_name='Grupo Meta')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.Componentes')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Pais')),
            ],
            options={
                'verbose_name': 'Dato General',
                'verbose_name_plural': 'Datos Generales',
            },
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_corto', models.TextField()),
                ('descripcion_completo', models.TextField()),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='ObjetivosResultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_corto', models.TextField()),
                ('objetivo_completo', models.TextField()),
            ],
            options={
                'verbose_name': 'Objectivo de resultado',
                'verbose_name_plural': 'Objectivo de resultados',
            },
        ),
        migrations.CreateModel(
            name='RegistroMeses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('meta', models.FloatField()),
                ('presupuesto', models.FloatField()),
            ],
            options={
                'verbose_name': 'Registro de mes',
                'verbose_name_plural': 'Registro de meses',
            },
        ),
        migrations.CreateModel(
            name='RegistroPlanAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('indicador2', models.CharField(max_length=250)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.Actividades')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.CategoriaGastos')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.Indicadores')),
            ],
            options={
                'verbose_name': 'Registro plan anual',
                'verbose_name_plural': 'Registros planes anuales',
            },
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tipo item',
                'verbose_name_plural': 'Tipos items',
            },
        ),
        migrations.CreateModel(
            name='UmbrelaDesempeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Rojo(<)'), (2, 'Verde(>)')])),
                ('aspecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.Aspectos')),
            ],
            options={
                'verbose_name': 'Umbrela de desempe\xf1o',
                'verbose_name_plural': 'Umbrelas de desempe\xf1os',
            },
        ),
        migrations.AddField(
            model_name='registroplananual',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.TipoItem'),
        ),
        migrations.AddField(
            model_name='registromeses',
            name='registro_anual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.RegistroPlanAnual'),
        ),
        migrations.AddField(
            model_name='indicadores',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.ObjetivosResultados'),
        ),
    ]
