# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsectores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervencion_corto', models.CharField(help_text='25 caracteres maximo', max_length=25)),
                ('intervencion_completo', models.TextField()),
            ],
            options={
                'verbose_name': 'Intervenci\xf3n',
                'verbose_name_plural': 'Intervenciones',
            },
        ),
        migrations.AlterModelOptions(
            name='categoriagastos',
            options={'verbose_name': 'Categoria de gasto', 'verbose_name_plural': 'Categorias de gastos'},
        ),
        migrations.AlterModelOptions(
            name='objetivosresultados',
            options={'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.RenameField(
            model_name='objetivosresultados',
            old_name='objetivo_completo',
            new_name='resultado_completo',
        ),
        migrations.RenameField(
            model_name='objetivosresultados',
            old_name='objetivo_corto',
            new_name='resultado_corto',
        ),
        migrations.RemoveField(
            model_name='objetivosresultados',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='macro_objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroplananual',
            name='resultado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subsectores.ObjetivosResultados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registromeses',
            name='mes',
            field=models.IntegerField(choices=[(1, '1er trimestre'), (2, '2do trimestre'), (3, '3er trimestre'), (4, '4to trimestre')], verbose_name='Trimestres'),
        ),
        migrations.AlterField(
            model_name='registroplananual',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.CategoriaGastos', verbose_name='Categoria de gastos'),
        ),
        migrations.AlterField(
            model_name='registroplananual',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.Indicadores'),
        ),
        migrations.AlterField(
            model_name='registroplananual',
            name='total_metas',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='registroplananual',
            name='total_presupuesto',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='intervenciones',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.DatosGenerales'),
        ),
        migrations.AddField(
            model_name='objetivosresultados',
            name='intervencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subsectores.Intervenciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroplananual',
            name='intervencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subsectores.Intervenciones'),
            preserve_default=False,
        ),
    ]
