# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('subsectores', '0002_auto_20170727_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('elaborado', models.CharField(max_length=50, verbose_name='Informe elaborado por:')),
                ('alcanzados_mes', models.IntegerField()),
                ('gastos_mes', models.IntegerField()),
                ('momento_indicador', models.IntegerField(choices=[(1, 'Proceso'), (2, 'Desarrollo'), (3, 'Cumplido')])),
                ('resultado', models.IntegerField()),
                ('informacion_cualitativa', models.TextField()),
                ('subir_archivo', models.FileField(upload_to='/media/informeMensual/')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.Indicadores')),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.Intervenciones')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsectores.DatosGenerales')),
            ],
            options={
                'verbose_name': 'Informe mensual',
                'verbose_name_plural': 'Informes mensuales',
            },
        ),
        migrations.AlterField(
            model_name='registroplananual',
            name='indicador',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='resultado', chained_model_field='objetivo', on_delete=django.db.models.deletion.CASCADE, to='subsectores.Indicadores'),
        ),
        migrations.AlterField(
            model_name='registroplananual',
            name='intervencion',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='proyecto', chained_model_field='proyecto', on_delete=django.db.models.deletion.CASCADE, to='subsectores.Intervenciones'),
        ),
        migrations.AlterField(
            model_name='registroplananual',
            name='resultado',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='intervencion', chained_model_field='intervencion', on_delete=django.db.models.deletion.CASCADE, to='subsectores.ObjetivosResultados'),
        ),
    ]
