# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsectores', '0004_auto_20170814_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informemensual',
            name='subir_archivo',
            field=models.FileField(upload_to='informeMensual'),
        ),
    ]
