# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0008_auto_20171002_1629'),
        ('subsectores', '0008_auto_20171002_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroplananual',
            name='es_socio',
            field=models.IntegerField(blank=True, choices=[(1, 'Socio directo'), (2, 'Socio estrat\xe9gico'), (3, 'Vecoma')], null=True),
        ),
        migrations.AddField(
            model_name='registroplananual',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.Organizacion'),
        ),
    ]
