# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_auto_20170620_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadosevaluacion',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='resultadosimplementacion',
            name='pais',
        ),
        migrations.AlterField(
            model_name='incrementoabastecimiento',
            name='tipo_mercado',
            field=models.IntegerField(choices=[(1, 'Tradicional'), (2, 'Feria'), (3, 'Local'), (4, 'Empresa comercializadora'), (5, 'Empresa procesadora'), (6, 'Empresas exportadoras'), (7, 'Supermercado'), (8, 'Cadena de restaurantes'), (9, 'Intermediarios')]),
        ),
    ]
