# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0004_auto_20170627_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='aumentadoingresos',
            name='precio_promedio_certificada',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aumentadoproductividad',
            name='precio_promedio_certificada',
            field=models.FloatField(default=0),
        ),
    ]
