# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0006_auto_20170714_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='aumentadoingresos',
            name='costos_promedio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aumentadoingresos',
            name='costos_promedio_certificada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadosimplementacion',
            name='grupo',
            field=models.IntegerField(blank=True, choices=[(1, 'Grupo de intervenci\xf3n'), (2, 'Grupo de control')], null=True),
        ),
    ]
