# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'verbose_name': 'Reportes y Proyectos', 'verbose_name_plural': 'Reportes y Proyectos'},
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('Reporte', 'Reporte'), ('Proyecto', 'Proyecto')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
